[build]
    publish = ".perseus/dist/exported"
    command = "yarn install_crates && yarn export && yarn export:post"

[[redirects]]
  from = "/.well-known/*"
  to = "/.perseus/:splat"
  status = 200
  force = true